---

- name: Generate configuration for each SRL node
  template:
    src: srl_config.j2
    dest: "{{ deployments_dir }}/{{ project_name }}/clabconfigs/{{ node.system_name }}.cfg"
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node
