---

- name: Add config_file entry to clab_topology.yml for each node
  template:
    src: "{{ topology_schema }}.j2"
    dest: "{{ deployments_dir }}/{{ project_name }}/clab_topology.yml"
  loop: "{{ nodes }}"
  loop_control:
    loop_var: node