---

- name: Check if deployments directory exists
  stat:
    path: "{{ deployment_dir }}"
  register: deployments_dir_stat

- name: Debug deployments_dir_stat
  debug:
    var: deployments_dir_stat

- name: Validate deployments directory exists
  assert:
    that: deployments_dir_stat.stat.isdir
    msg: "Deployments directory {{ deployment_dir }} does not exist"
