---
- name: Initialize project environment
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Check for Ansible version
      assert:
        that: "ansible_version.full is version_compare('2.18.1', '==')"
        msg:  "Ansible version 2.18.1 is required. Found Ansible version {{ansible_version.full}}"

  tasks:
    - include_role:
        name: build

    - include_role:
        name: common
      
    - name: Import Playbook create_topology.yml
      debug:
        msg:
          - "************************************************"
          - "Import CLAB Create Topology Playbook"
          - "************************************************"

- name: Import Playbook -> create_topology.yml
  import_playbook: create_topology.yml
