---
- name: Create topology file
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Import Playbook create_topology.yml
      debug:
          msg:
          - "************************************************"
          - "Import CLAB Topology Role"
          - "************************************************"

    - include_role:
        name: clab-topology
