name: Validate SR Linux Configurations

on:
  push:
    paths:
      - clabconfigs/nokia/srl/**

jobs:
  SRL-deploy:
    name: Validate Configurations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Containerlab
        run: |
          curl -sL https://get.containerlab.dev | sudo bash
          containerlab version

      - name: Install Docker Images
        run: |
          docker pull ghcr.io/nokia/srlinux

      - name: Validate config on SRL1
        run: sudo containerlab deploy -t clabtopology/nokia/single_node.yml

      - name: Insect CLAB Topology
        run: |
          echo "Validating topology file"
          sudo containerlab inspect -t clabtopology/nokia/single_node.yml

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          python3 -m pip install --upgrade pip
          pip install paramiko pyyaml
    
      - name: Destroy containerlab topology
        if: always()
        run: |
          sudo clab destroy --topo clabtopology/nokia/single_node.yml
